"""Generate gui/assets/emblems_data.js from the bundled tier emblem WebPs.

Reads gui/assets/emblems/{tier}.webp for all 11 tiers, base64-encodes each,
and writes a plain JS file defining `const EMBLEM_B64 = {...}`. Loaded once
via a <script> tag in index.html (RANK-05, D-03) — never re-transmitted
through window.state (Pitfall 3).

Stdlib only (base64, json, os) — no Pillow/requests/numpy.

Re-run any time:  py scripts/gen_emblems.py
"""
import base64
import json
import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(REPO_ROOT, "gui", "assets", "emblems")
OUT_FILE = os.path.join(REPO_ROOT, "gui", "assets", "emblems_data.js")

TIERS = [
    "iron", "bronze", "silver", "gold", "platinum", "emerald",
    "diamond", "master", "grandmaster", "challenger", "unranked",
]

data = {}
for tier in TIERS:
    path = os.path.join(SRC_DIR, f"{tier}.webp")
    with open(path, "rb") as fh:
        data[tier] = base64.b64encode(fh.read()).decode("ascii")

with open(OUT_FILE, "w", encoding="utf-8") as fh:
    fh.write("/* Generated by gen_emblems.py — do not edit by hand. */\n")
    fh.write(f"const EMBLEM_B64 = {json.dumps(data)};\n")

print(f"wrote {OUT_FILE} ({sum(len(v) for v in data.values())} base64 chars, {len(data)} tiers)")
